/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */


import {
  RangeTest as MsrdRangeTest
} from './components/range-test/range-test';

declare global {
  interface HTMLMsrdRangeTestElement extends MsrdRangeTest, HTMLElement {
  }
  var HTMLMsrdRangeTestElement: {
    prototype: HTMLMsrdRangeTestElement;
    new (): HTMLMsrdRangeTestElement;
  };
  interface HTMLElementTagNameMap {
    "msrd-range-test": HTMLMsrdRangeTestElement;
  }
  interface ElementTagNameMap {
    "msrd-range-test": HTMLMsrdRangeTestElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "msrd-range-test": JSXElements.MsrdRangeTestAttributes;
    }
  }
  namespace JSXElements {
    export interface MsrdRangeTestAttributes extends HTMLAttributes {
      max?: number;
      min?: number;
      value?: number;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
